#!/usr/bin/env bash

read -d '' packages <<"EOF"
Zen
atom-material-syntax
atom-material-ui
auto-detect-indentation
autocomplete-paths
circle-ci
color-picker
file-icons
highlight-line
highlight-selected
language-agda
language-apache
language-docker
language-elixir
language-erlang
language-haml
language-haskell
language-jade
language-julia
language-latex
language-lisp
language-lua
language-nginx
language-purescript
language-rust
language-scala
language-swift
linter
linter-clojure
linter-csslint
linter-jshint
linter-jsxhint
markdown-pdf
merge-conflicts
minimap
minimap-find-and-replace
minimap-highlight-selected
neutron-syntax
neutron-ui
nuance-dark-syntax
nuance-dark-ui
pigments
pretty-json
react
regex-railroad-diagram
script
todo-show
trailing-spaces
EOF

case "${1}" in
  init) mkdir -p ~/.atom/packages ;;

  install)
    comm -13 <(apm list --bare --installed | ghead -n -1 | cut -f1 -d'@' | sort) <(echo "${packages}" | sort) | xargs apm install
  ;;

  sync)
    ${0} uninstall
    ${0} install
  ;;

  uninstall)
    comm -13 <(echo "${packages}" | sort) <(apm list --bare --installed | ghead -n -1 | cut -f1 -d'@' | sort) | xargs apm uninstall
  ;;

  *) echo 'Command not found' ; exit 1 ;;
esac

exit 0
