#!/usr/bin/env bash

# TODO: When one of these, brew install with options
curl='curl --with-libidn --with-libssh2'
git='git --with-brewed-curl --with-brewed-openssl'
gnupg='gnupg --8192'
gnupg2='gnupg2 --8192'
imagemagick='imagemagick --with-webp'
scala='scala --with-docs --with-src'
wget='wget --enable-iri'
wireshark='wireshark --with-qt'

read -d '' brews <<"EOF"
ansible
archey
awscli
asciinema
bash-completion
bats
bcrypt
coreutils
curl
docker
docker-compose
docker-machine
docker-swarm
elixir
exiftool
ffmpeg
findutils
flow
fswatch
gcc
git
git-lfs
git-extras
github-crypt
gnu-sed
gnu-tar
gnupg
gnupg2
go
gradle
heroku-toolbelt
httpie
hub
imagemagick
jq
kubernetes-cli
mitmproxy
moreutils
nmap
nvm
openssl
optipng
python
rbenv
redis
rfc
ruby
scala
slack-cli
socat
spark
ssh-copy-id
vim
watchman
wget
wireshark
EOF

case "${1}" in
  init)
    brew tap homebrew/dupes
    brew tap homebrew/science
    brew tap rockymadden/rockymadden
  ;;

  install)
    brew update
    comm -13 <(brew list -1 | sed 's|rockymadden/rockymadden/||' | sort) <(echo "${brews}" | sort) | xargs brew install
  ;;

  sync)
    ${0} uninstall
    ${0} install
  ;;

  uninstall)
    brew update
    comm -13 <(echo "${brews}" | sort) <(brew leaves | sed 's|rockymadden/rockymadden/||' | sort) | xargs brew uninstall
  ;;
esac
