#!/usr/bin/env bash

# taps
brew tap caskroom/cask
brew tap caskroom/versions

# update, upgrade, and cleanup
brew update
brew upgrade
brew cleanup

# brew cask
brew cask install 1password
brew cask install atom
brew cask install cloud
brew cask install fantastical
brew cask install firefox
brew cask install gitup
brew cask install google-chrome
brew cask install google-earth
brew cask install istat-menus
brew cask install iterm2
brew cask install kitematic
brew cask install skype
brew cask install slack
brew cask install the-unarchiver
brew cask install transmission
brew cask install vagrant
brew cask install virtualbox
brew cask install vlc

# brew fonts
brew cask install font-alegreya
brew cask install font-anonymous-pro
brew cask install font-droid-sans
brew cask install font-droid-serif
brew cask install font-exo
brew cask install font-exo2
brew cask install font-fontawesome
brew cask install font-istok-web
brew cask install font-karla
brew cask install font-lato
brew cask install font-lora
brew cask install font-merriweather
brew cask install font-nobile
brew cask install font-open-sans
brew cask install font-pt-mono
brew cask install font-pt-sans
brew cask install font-pt-serif
brew cask install font-raleway
brew cask install font-raleway-dots
brew cask install font-roboto
brew cask install font-source-code-pro
brew cask install font-source-sans-pro
brew cask install font-ubuntu
