#!/bin/bash

# ---------------------------------------------------------------------------------------------------------------------
# Set up:
# ---------------------------------------------------------------------------------------------------------------------

brew tap caskroom/cask
brew tap caskroom/versions
brew install brew-cask

# ---------------------------------------------------------------------------------------------------------------------
# Update and upgrade:
# ---------------------------------------------------------------------------------------------------------------------

brew update && brew upgrade brew-cask && brew cleanup

# ---------------------------------------------------------------------------------------------------------------------
# Install:
# ---------------------------------------------------------------------------------------------------------------------

brew cask install 1password
brew cask install atom
brew cask install cloud
brew cask install fantastical
brew cask install firefox
brew cask install gitup
brew cask install google-chrome
brew cask install google-earth
brew cask install istat-menus
brew cask install iterm2
brew cask install kitematic
brew cask install onyx
brew cask install skype
brew cask install slack
brew cask install the-unarchiver
brew cask install transmission
brew cask install vagrant
brew cask install virtualbox
brew cask install vlc
