#!/bin/bash

nvm install node
nvm use node
npm install -g babel
npm install -g bower
npm install -g grunt-cli
npm install -g gulp
npm install -g jest-cli
npm install -g node-notifier
npm install -g ramda-cli

nvm install 0.12
nvm use 0.12
npm install -g babel
npm install -g bower
npm install -g grunt-cli
npm install -g gulp
npm install -g jest-cli
npm install -g node-notifier
npm install -g ramda-cli

nvm install 0.10
nvm use 0.10
npm install -g babel
npm install -g bower
npm install -g grunt-cli
npm install -g gulp
npm install -g jest-cli
npm install -g node-notifier
npm install -g ramda-cli
